# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: env
    jobs:
      - job: Nodes
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.13.1'
            displayName: 'Install Node.js'

  - stage: build
    jobs:
      - job: build_site
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
          - script: |
              export
              npm run build

      - job: upload_package
        steps:
          - task: CopyFiles@2
            inputs:
              contents: |
                dist
              targetFolder: $(Build.ArtifactStagingDirectory)
            displayName: 'Copy archives to artifacts staging directory'

          - task: PublishBuildArtifacts@1
            inputs:
              path: $(Build.ArtifactStagingDirectory)
#              artifact: publish
            displayName: 'Publish artifacts'

        dependsOn: build_site
        condition: and(succeeded(), startsWith(variables['System.PullRequest.SourceBranch'], 'release/'))
